name: Lock closed inactive issues

on:
  schedule:
    # Run at 16:00 every day
    - cron: '0 16 * * *'

jobs:
  lock_closed:
    if: github.repository == 'angular/angular'
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@9291298d2fb9f6abe1b47784f14b99bd9a4fa53b
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
